### PR TITLE
add variables for icons and navigation labels

### PR DESCRIPTION
**Pull request by taramk**
* create a firmer definition between icons and secondary icons and assign icons in the app accordingly
* add variables for nav icons and nav labels to make theming a little more fun

color-nav-label is a semantic label like color-sidebar-background, i think it is okay since these are specific to the UI and not part of a broader pattern (yet).

### CODE REVIEW

**Comment by progrium** [comment]
Looks good. For future (and refactoring existing if you want), name partials like "maincontent" should be simplified to "main" or "content" depending on what makes sense given sibling names in the ontology. Together they are redundant. Similarly, "bottomsection" should probably be simplified to "bottom" since ultimately all elements are "sections".

**Comment by progrium** [comment]
Also, what I said about reversing name parts applies to the whole name. By using "color-background-sidebar" instead of "color-sidebar-background", sorting by name gives a useful scannable taxonomy. While there can be exceptions to create a taxonomy that indexes more easily for a functional group, and sidebar could be one of them, consistent repeating patterns like secondaries should definitely follow this lexicographical ordering, for example "color-secondary-icon" should probably be "color-icon-secondary" etc.

**Comment by progrium** [comment]
We also want to make names short because they are frequently combined. So while with "color-icon-secondary" might imply we should be using "color-icon-primary", I do prefer the brevity of what we have now with just "color-icon". As a suggestion, though I don't feel strongly, I'm curious how "2nd" feels instead of "secondary" as a shorter form. I previously suggested "alt", which could work in some cases, but usually secondary is part of a scale not a swappable "alternative". Though it could also be interpreted as "alternating".

**Comment by taramk** [comment]
@progrium - i can adjust names so it's type-noun-adjective/descriptor.

i'd like to leave secondary for now, i think it has the clearest meaning and i'd rather optimize for that rather than character length, since it's not something people will be editing super often.

**Comment by progrium** [comment]
👍

**Pull request merged**
